import { releaseConfig } from "@/lib/release-config";

export const TERMS_SECTIONS = [
  { title: "About these terms", text: `These terms cover your use of Unravel: the website, the web journal and the mobile app. Unravel is operated by ${releaseConfig.ownerName}. By creating an account, starting a guest journal or otherwise using the app, you agree to them. If you do not agree, please do not use Unravel.` },
  { title: "Who can use Unravel", text: "Unravel is for people aged 13 and over. Creating an account or starting a guest journal asks for your date of birth to confirm this. If we learn that an account belongs to someone under 13, we delete the account and its journal. If you are under the age of majority where you live, please read these terms with a parent or guardian." },
  { title: "Unravel is not medical care", text: "Unravel is a journaling and general wellbeing app. It is not a medical device, not medical or mental-health treatment, not a diagnosis, and not an emergency service. Nothing in the app is professional advice. AI reflections, prompts, suggested readings and music are generated automatically and can be inaccurate or unhelpful. Do not rely on Unravel in an emergency. If you are in crisis or may be at risk of harming yourself or someone else, contact your local emergency number or a crisis line immediately." },
  { title: "Your account", text: "You are responsible for keeping your sign-in details and any device passcode for the app confidential, and for activity that happens under your account. Use accurate information when you sign up and keep your email address current so password resets reach you. Tell us promptly if you believe someone else has accessed your account." },
  { title: "Your journal content", text: "Your entries, recordings, moods and other journal content remain yours. You give Unravel only the permission needed to operate the app for you: to store, process, back up and display your content so you can use the features you have chosen. We do not sell your journal content, use it for advertising, or publish it. Optional AI features send content to processors only when you have turned them on, as described in the privacy policy." },
  { title: "Acceptable use", text: "Please use Unravel only for your own journaling and wellbeing. Do not use it to break the law, to store or share content you have no right to, to harass or harm anyone, or to upload malware. Do not attempt to access other people's accounts or journals, probe or disrupt the service, scrape it, bypass security or rate limits, or reverse engineer the app except where the law expressly allows it." },
  { title: "Optional features and third parties", text: "Some features depend on outside services: AI reflections and transcription, personalized reading searches, and music information and previews. These are optional and off until you turn them on. When you open an external link or play a preview, you are using someone else's service under their terms and privacy policy. Unravel does not control that content and is not responsible for it. Features may change, and outside services can become unavailable." },
  { title: "Availability and changes", text: "Unravel is offered as it is and as available, and is still in preparation for launch. We may add, change, suspend or remove features, and there may be downtime, maintenance or data-sync delays. We try to avoid losing anything, but you should keep your own copies of anything you cannot afford to lose. You can export your journal at any time from Settings." },
  { title: "Ending your use", text: "You can stop using Unravel whenever you like and delete entries or your whole account in Settings → Account. Deleting your account removes the authentication account, associated database records and stored voice recordings from active app storage, as described in the privacy policy. We may suspend or end access to an account that breaks these terms, that we must act on for legal reasons, or that puts other people or the service at risk." },
  { title: "Disclaimers and liability", text: "To the extent the law allows, Unravel is provided without warranties of any kind, and the operators are not liable for indirect, incidental or consequential loss, lost data, or loss arising from your reliance on AI output or other automated suggestions. Nothing here limits liability that cannot be limited by law, including for death or personal injury caused by negligence, or for fraud. Some jurisdictions do not allow certain exclusions, so parts of this section may not apply to you, and you may have consumer rights that these terms do not affect." },
  { title: "Privacy", text: "How your information is handled is described in the privacy policy, which forms part of these terms. It explains what is stored, which processors are involved, what the optional AI features share, and how to export or delete your journal." },
  { title: "Changes to these terms", text: "We may update these terms as the app changes. The date at the top of this page shows the most recent update. If a change matters, we will try to give reasonable notice in the app. Continuing to use Unravel after an update means you accept the revised terms." },
] as const;
