export const AI_SHARING_NOTICE = "Allow Unravel to send journal text, moods, feelings and relevant profile preferences to Google Gemini for AI reflections and label corrections; voice recordings to Groq for transcription, including automatically when you save a voice entry with AI enabled; and long transcripts to Google Gemini for summaries. Personalized reading searches send topic and profile-derived queries to Google Custom Search. Music lookups send artist and genre queries to Deezer. These services process the data to provide the requested features. You can turn this off in Settings at any time. Journaling, recording, breathing and Supabase account sync still work with it off.";

export const PRIVACY_SECTIONS = [
  { title: "Public website and support", text: "You can read the public website, privacy policy and support page without signing in. These pages do not start a Supabase journal session. Fonts are served with the website. When the website is hosted on Vercel, Vercel processes network and request information to deliver and secure it. If you contact support, the operators and email provider process your email address and the information you send to respond to your request. Please do not send passwords or private journal entries." },
  { title: "Your account and journal", text: "Unravel uses Supabase for account authentication, database storage and private voice-recording storage. This includes your email address if supplied, profile preferences, journal text, moods, energy, feelings, recordings, transcripts, saved suggestions and reminder settings. Guest journals also use a Supabase account. Your journal is not public or shared with other users. It is not end-to-end encrypted: service providers process data to operate the app." },
  { title: "Optional AI and recommendations", text: AI_SHARING_NOTICE },
  { title: "Reminders and email", text: "Device notifications are scheduled locally after you request permission. Optional reminder emails are sent through Google's Gmail API and include your email address, display name and reminder message, not your journal text. Supabase authentication emails are delivered through the email service configured for the app's Supabase project." },
  { title: "External content", text: "Deezer supplies music information, artwork and audio previews. Loading artwork or playing previews connects your device to its servers, which receive network information such as your IP address. Opening a reading or music link takes you to an external service with its own privacy policy. Unravel does not operate those websites." },
  { title: "Analytics and device storage", text: "This version has no advertising or dedicated analytics SDK. Supabase and other infrastructure providers may retain operational, security and request logs. The app stores sign-in sessions, unfinished drafts and preferences on your device. Journal mood and activity insights are app features. An administrator dashboard also shows aggregate usage and mood/energy statistics and pseudonymous changes over time for individual accounts. These are used to understand app usage and wellbeing trends, not for advertising. Exporting creates a separate file that you control." },
  { title: "Your choices and deletion", text: "You can decline microphone or notification access and continue using the app. Turn off AI suggestions to stop new optional sharing; this cannot recall data already processed. You can export your journal, permanently delete entries, or delete your account in Settings → Account. Account deletion removes the authentication account, associated database records and stored voice recordings from active app storage. Separate exports and provider backups or logs are not erased by the app's account-deletion action; their retention depends on the configured providers. Recently deleted entries remain recoverable until permanently removed." },
  { title: "Wellbeing and audience", text: "Unravel is a journaling and general wellbeing app, not a medical service or emergency service. AI reflections can be inaccurate and are not diagnosis or treatment. The app is not submitted in Apple's Made for Kids category." },
] as const;
